baseURL = "https://suitecrm-docs.netlify.com"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Suite CRM Documentation"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false

[params]
  editURL = "https://github.com/Accendere/SuiteDocs/edit/master/content/"
  description = "Documentation for SuiteCRM"
  author = "Frank Taillandier"
  showVisitedLinks = false
  themeVariant = "suitecrm"

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
section = [ "HTML", "AMP", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "SuiteCRM Documentation"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-newspaper-o'></i> Blog"
url = "blog"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-github'></i> Github"
identifier = "ds"
url = "https://github.com/salesagility/SuiteCRM"
weight = 11


# [[Languages.en.menu.shortcuts]]
# name = "<i class='fa fa-bookmark'></i> Hugo Documentation"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fa fa-bullhorn'></i> Credits"
# url = "/credits"
# weight = 30

[Languages.fr]
title = "Documentation de SuiteCRM"
weight = 2
languageName = "Français"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-github'></i> Github"
identifier = "ds"
url = "https://github.com/salesagility/SuiteCRM"
weight = 10

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fa fa-camera'></i> Vitrine"
# url = "/showcase"
# weight = 11

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fa fa-bookmark'></i> Documentation Hugo"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fa fa-bullhorn'></i> Crédits"
# url = "/credits"
# weight = 30
