baseURL = "https://docs.suitecrm.com"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "SuiteCRM Documentation"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false
enableGitInfo = true
timeout = 47000
ignoreErrors = ["error-remote-getjson"]

[params]
  GitHubRepo  = "https://github.com/salesagility/SuiteDocs/"
  editURL     = "https://github.com/salesagility/SuiteDocs/edit/master/content/"
  issueURL    = "https://github.com/salesagility/SuiteDocs/issues/new?"
  title       = "Documentation for SuiteCRM"
  description = "All you need to know to successfully use SuiteCRM as an End-User, Developer or Administrator, plus Community Guidelines and Technical Blog."
  images      = ["https://docs.suitecrm.com/images/logo-square.png"]
  author      = "SalesAgility"
  showVisitedLinks = true
  themeVariant = "suitecrm"

[outputs]
home = [ "HTML", "RSS", "JSON"]
section = [ "HTML", "RSS"]

[Languages]

# ------------------------------------------------------------
# ------------------ ENGLISH ---------------------------------
# ------------------------------------------------------------

[Languages.en]
# the following site title appears as PageTitle :: SiteTitle on every page; it will be the tab name on the browser
title = "SuiteCRM Documentation"
#title = "Docs"
weight = 1
languageName = "English"
languageDir = "/"

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-newspaper-o'></i> Blog"
url = "blog"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/salesagility/SuiteCRM"
weight = 11


# [[Languages.en.menu.shortcuts]]
# name = "<i class='fa fa-bookmark'></i> Hugo Documentation"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

# ------------------------------------------------------------
# ------------------ SPANISH ---------------------------------
# ------------------------------------------------------------

[Languages.es]
title = "Documentación de SuiteCRM"
weight = 2
languageName = "Español"
languageDir = "/es/"

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/salesagility/SuiteCRM"
weight = 10

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-newspaper-o'></i> Blog"
url = "blog"
weight = 10

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/salesagility/SuiteCRM"
weight = 11

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Gracias"
url = "/credits"
weight = 30

# [[Languages.es.menu.shortcuts]]
# name = "<i class='fa fa-camera'></i> Vitrine"
# url = "/showcase"
# weight = 11

# [[Languages.es.menu.shortcuts]]
# name = "<i class='fa fa-bookmark'></i> Documentation Hugo"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

# ------------------------------------------------------------
# ------------------ RUSSIAN ---------------------------------
# ------------------------------------------------------------

[Languages.ru]
title = "SuiteCRM - Русскоязычная документация"
weight = 3
languageName = "Русский"
languageDir = "/ru/"
